# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureDeployLinkedTemplatePipelineConnection'
    subscriptionId: 'e9411a02-d139-4506-86fe-178e36e5c3be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-deployLinkedTemplate-test'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Aissous-Amin/azure-deploy-linked-template/main/azureDeploy.json'
    overrideParameters: '-projectName azure-deploy-linked-template'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
